name: CI

on:
  #push:
    #branches: [ "main" ]
  schedule:
    - cron: "0 */11 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: checkout
        run: |
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${{ github.token }}@github.com/${{ github.repository }} .
          git sparse-checkout init --cone --sparse-index
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      
      - name: atuo-green
        run: |  
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf *.txt
          DATE=`date +%Y%m%d%H%M`
          touch $DATE.txt
          git add .
          git commit --allow-empty -m "a commit a day "
          git push --force https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main

