name: CI

on:
  #push:
    #branches: [ "main" ]
  schedule:
    - cron: "0 */11 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: |
          git config --global --add safe.directory $(pwd)
          git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
        
          ref_type=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/([^/]*)\/.*$/\1/p')
          ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
          
          case $ref_type in
            pull)
              git fetch origin +refs/pull/$ref:refs/remotes/origin/pull/$ref
              ref="origin/pull/$ref"
              ;;
            *)
              ref=${{ github.sha }}
              ;;
          esac
          
          git checkout $ref
          
          #BRANCH="${GITHUB_REF/#refs\/heads\//}"
          #git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${{ github.token }}@github.com/${{ github.repository }} .
          #git sparse-checkout init --cone --sparse-index
          #git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          #git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf *.txt
          DATE=`date +%Y%m%d%H%M`
          touch $DATE.txt
          git add .
          git commit --allow-empty -m "a commit a day "
          git push --force https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main

